# Generated by Django 4.2.1 on 2023-08-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uemail', models.CharField(max_length=100)),
                ('port', models.CharField(max_length=100)),
                ('res', models.CharField(max_length=100)),
                ('web', models.CharField(max_length=100)),
                ('linked', models.CharField(max_length=100)),
                ('insta', models.CharField(max_length=100)),
                ('fb', models.CharField(max_length=100)),
                ('hack', models.CharField(max_length=100)),
                ('codechef', models.CharField(max_length=100)),
                ('leet', models.CharField(max_length=100)),
                ('gthub', models.CharField(max_length=100)),
                ('gfg', models.CharField(max_length=100)),
            ],
        ),
    ]
