# Generated by Django 4.2.1 on 2023-08-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linktreeapp', '0002_userdetails_desg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='usname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
